Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,35 @@
+name: "CI"
 
+on:
+  push:
+    branches:
+        - master
+        - CI_testing
+  pull_request:
+    branches:
+        - master
+
+jobs:
+  macOS:
+    name: "macOS (ARM, latest)"
+
+    runs-on: macos-latest
+    steps:
+      - name: Install dependencies
+        run: |
+          # Use a strict shell, stop the interpreter on various errors,
+          # so errors such as undefined variables are caught by CI/CD
+          # instead of ignored. Use printf because it contains options,
+          # which can be difficult to escape.
+          printf "%s\n" "set -euo pipefail" >> ~/.zprofile
+
+          # For #!/bin/bash scripts.
+          # To ensure ~/.bash_env is executed, BASH_ENV must be set for the
+          # current default shell of which bash is launched from.
+          # Use a special ~/.bash_env file because ~/.bash_profile
+          # may contain commands that reset environment variables
+          # such as PATH.
+          printf "%s\n" "set -euo pipefail" >> ~/.bash_env
           echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.zprofile
 
           # GitHub's default ~/.bash_profile contains:
